apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-website-deployment
  labels:
    app: example-website-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-website-deployment
  template:
    metadata:
      labels:
        app: example-website-deployment
    spec:
      containers:
        - name: example-website
          image: example.azurecr.io/example:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: example-web-prod-env
          env:
            - name: PORT
              value: "8001"
          ports:
            - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: example-website-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: example-website-deployment